using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;

namespace MvvmPractice
{
    // INotifyPropertyChanged is implemented by ObservableObject
    internal partial class ViewModel : ObservableObject
    {
        private ConfigModel _config;

        // public "Volume" property is automatically generated by [ObservableProperty]
        [ObservableProperty]
        private int _volume;

        // OnVolumeChanged() is called when Volume property is changed  
        partial void OnVolumeChanged(int value) {
            _config.Volume = value;
            _config.SaveConfig();
        }

        public ViewModel()
        {
            _config = new ConfigModel();
            _volume = _config.Volume;
        }
    }
}
