using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;

namespace MvvmPractice
{
    // INotifyPropertyChanged is implemented by ObservableObject
    internal partial class ViewModel : ObservableObject
    {
        private ConfigModel _config;

        // public "Volume" property is automatically generated by [ObservableProperty]
        [ObservableProperty]
        private int _volume;

        [ObservableProperty]
        private int _brightness;

        // OnVolumeChanged() is called when Volume property is changed  
        partial void OnVolumeChanged(int value) {
            _config.Volume = value;
            _config.SaveConfig();
        }

        partial void OnBrightnessChanged(int value)
        {
            _config.Brightness = value;
            _config.SaveConfig();
        }

        // public "DoubleVolumeCommand()" method is automatically generated by [RelayCommand]
        [RelayCommand]
        private void DoubleVolume()
        {
            Volume *= 2;
        }
        // Rewrite DoubleVolume() using lambda expression
        // private void DoubleVolume() => Volume *= 2;

        [RelayCommand]
        private void TripleVolume()
        {
            Volume *= 3;
        }

        public ViewModel()
        {
            _config = new ConfigModel();
            _volume = _config.Volume;
            _brightness = _config.Brightness;
        }
    }
}
